### ISSUE TITLE
installer / lobby: stuck in "startup directory is not writeable!" loop

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#608]
As described in http://zero-k.info/Forum/Thread/14163
(seems to be a known problem but I did not find it on git bugtracker)

"Any attempts at launching result in this error popping up over and over again until the task is force closed:
[Startup directory is not writeable!]"
http://i.imgur.com/JA3SgGk.jpg

This post has collected similiar threads and more info:
http://zero-k.info/Forum/Thread/14163#126321

**Comment by Anarchid** [comment]
Collating from sheep's [inquiry](http://zero-k.info/Forum/Thread/14163#126321) on the problem:

> Anyway, the error is not issued by the installer, but by ZKL itself:
>https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/ZeroKLobby/Program.cs#L161
>An interesting condition:
> StartupPath.Contains("Local\\Apps")
>look again at OP's screenshot...
>Then here:
>https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/ZeroKLobby/Program.cs#L171
>So, zero-k.exe is moved to ...local\apps\... then started again, then of course, when its checking whether it is in local\apps, it complains again...

**Comment by xponen** [comment]
useful debugging!

**Comment by xponen** [comment]
fix have been commited https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/e44f92af095b1ed5161c6995119a42253af16b95

very much thanks to [v]sheep for researching the fix!. 

IMO this bug happen because new user choose ClickOnce version, which installed ZKL into Local/apps first then immediately update to recent one that do not use Local/apps, but Spring directory wasn't set yet so ZKL have no place to write to except into Local/apps again.

**Comment by xponen** [comment]
hopefully fixed in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/e44f92af095b1ed5161c6995119a42253af16b95 
which tell ZKL to ask for Spring dir if current dir is Local/apps

**Comment by Orfelius** [comment]
Apperently bug still exists but it is no longer a loop.
I have installed it on my brother's computer today and it gave me following error:
Setup directory is not writeable
Please use the newely created desktop icon to start Zero-K not this one.
Zero-K will be moved to C:\Users\xxx\My Documents\...

then it writes another error:

Move failed, please copy Zero-K.exe into writeable folder

And then it proceeds to work anyway. And yes I tried to both use the launcher directly as well as the created icon. It gives the same result.

**Comment by knorker** [comment]
@Orfelius 
Open new issue then.

or
@xponen should re-open this one. (I can not, because http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github )

**Comment by Stuart1998** [comment]
Issue is not fixed, please reopen.

**Comment by KingRaptor** [comment]
Removed the ClickOnce installer (and all references to 91.0) from the download page.

**Comment by KingRaptor** [comment]
I'm assuming this is fixed. If it occurs with the non-ClickOnce installer (now the only one available) please post here.

**Comment by Anarchid** [comment]
This happens on my windows partition but i'm not sure which installer i used. I will reinstall for science sometime this ~~week~~ year.
