### ISSUE TITLE
website -> nominate for clan leader is allowed when in no clan -> error

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#637]
http://pastebin.com/g8MQ0P8C

**Comment by KingRaptor** [comment]
Fixed on next site deploy, thanks for reporting!

**Comment by mojjj** [comment]
someone puke site to rebuid/deploy, it is still failing with style.
