### ISSUE TITLE
Mac version does not exist

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#759]
http://zero-k.info/Wiki/Download has a Mac section:
![bla](https://cloud.githubusercontent.com/assets/3044855/9536149/096a2c12-4d29-11e5-845d-0e1e0ba9b7af.png)

http://weblobby.springrts.com/ has a "Download" link that points to a google-drive folder:

https://415a950abc581c1790471984449656708f118b03.googledrive.com/host/0Bys6k7VMCRfUZ0N5MGJXR1pRV2M/

Inside are Windows & Linux files.

No Mac version.

**Comment by knorker** [comment]
Also this sentence makes no sense at all to me:

"If you're using Linux you might need to download version 98.0.1-451-g0804ae1 from the Help tab. "

1) Why does it mention Linux in section of Mac OS X? 
2) game does not use such engine version since long time.
3) In the "Help tab" of weblobby there is no way to download anything. 

In https://springrts.com/phpbb/viewtopic.php?f=65&t=32970&p=573308#p573308 are some attempts to get spring engine working again on Mac, but seems nothing released so far. (no Mac on https://springrts.com/wiki/Download )
Does zK even work on Mac? If not, put some note "Sorry, not playable on Mac at the moment."

**Comment by db81** [comment]
@flxK actually got swl and zk working on a Mac and detailed it in http://zero-k.info/Forum/Thread/19682?postID=137929.

The 98.0.1-451 engine help tab thing is long obsolete.

**Comment by knorker** [comment]
Ah nice. Seems very experimental though, I doubt players can manage that.
Already the first step "1. Download spring 100.0 for OSX" is impossible if you do not know about https://springrts.com/dl/buildbot/default/master/100.0/  ?
Having to manually extract files, start lobby then close it again etc...

Are his modifications now in official weblobby, too? On weblobby homepage I see no Mac download.
Downloads from third party sites ( http://www.felix-kraus.net/files/zero-k/zero-k_OSX.zip ) is not good imo.

**Comment by flxK** [comment]
If you don't trust my download link, you can just download qt creator, import swl-qt from github and build your own version of swl (use Qt 5.5.0 clang).

**Comment by knorker** [comment]
Hi
For me it is not about trust in the code (though it might be for others, maybe license too) but if http://www.felix-kraus.net/files/zero-k/zero-k_OSX.zip is not linked on download page then no player will ever know about it.
'Foreign' homepages are imo not so reliable..compare with zK homepage and manual: People hosted images in dozen of random places and result is/was/will be many broken pictures.

**Comment by flxK** [comment]
The problem is that it was not an official build. It was also coded with some workarounds. The actual git version could be released as stable build.

**Comment by flxK** [comment]
@db81 Who should i ask in order to get the download section edited? I asked in #zkdev, but it was ignored.

**Comment by db81** [comment]
I don't see any messages in #zkdev, which is weird since even if you posted in #zkdev on the old server it should have still relayed the message.

The downloads page is a wiki page so it's probably easiest to wait until wiki is finished (which should be soon) and then edit it.

**Comment by flxK** [comment]
Okay, i asked about 2 months ago. It think because of that you did not find the message.

**Comment by Licho1** [comment]
Cleaned up download pages and removed MAC mentions

**Comment by knorker** [comment]
Why remove all mentions of Mac, when someone had just posted functional Mac stuff...
Is there no interesst in Mac support?
By the way, now the file is gone:

http://www.felix-kraus.net/files/zero-k/zero-k_OSX.zip - The requested URL /files/zero-k/zero-k_OSX.zip was not found on this server.

**Comment by Licho1** [comment]
Personally  I don't have any mac to test stuff, we need mac person to test and maintain it and put instrucitons to wiki... not much i can do atm..

**Comment by db81** [comment]
I agree that this stuff should be mentioned in wiki. I think it will be fine if it's designated as unofficial and relies on @flxK keeping it up to date.

AFAIK there still aren't official engine builds for Mac, and no one got ZKL working there either.

**Comment by knorker** [comment]
> Personally I don't have any mac to test stuff, we need mac person to test and maintain it 
> and put instrucitons to wiki... not much i can do atm..
With flxK there IS a mac person!

So much potential wasted with all this organisation fail.

**Comment by flxK** [comment]
I just reuploaded the zip on my server (forgot it after reinstallation).
I am now playing since september using this engine version and my weblobby build, without having any seriois problem.
Maybe someone noticed that i also pushed some code to the qt and to the website repositories of weblobby.
Everyboady should be able to make a build using qt-creator.

**Comment by flxK** [comment]
If someone wants to test it, i could provide an account on my mac. One of you could connect using vnc and test the functionality.

**Comment by knorker** [comment]
http://zero-k.info/Wiki/MacHowto again/still broken.

>  1 Download Weblobby: https://drive.google.com/folderview?id=0BwbAiEHn4hRmak85MmlRR05SM3M&usp=sharing

-> folder does not exist

> 2 Download Spring engine 100.0 for OSX: ...

-> Since some months zero-K does not use engine 100.0

> http://www.felix-kraus.net/files/zero-k/zero-k_OSX.zip 

-> The requested URL /files/zero-k/zero-k_OSX.zip was not found on this server.

**Comment by Licho1** [comment]
fixed
