### ISSUE TITLE
Website search option is super-weird(-useless)

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K-Infrastructure#871]
To clarify: this is about the search input field in the top-right of zero-k.info and not about the forum's "Filter" input field.

Type in a word or two and chances are most of the results do not even include any of the words. Example: I type "balance" and "algorithm", then get a list of links to forum threads (the 100 results probably only cover 10 different threads). When I open a few of the links and Ctrl+F for "balance" my browser returns 0 results, same for "algorithm".

I would expect this search function to **at least** return links that contain any of the words I searched for. Better if results were sorted by how many of the words were found, or if the order of multiple words were the same. (eg. "*this is zk*" would return a thread titled "welcome *this is zk*, enjoy your stay" above "*this* can be the reason why *zk* *is* fun")

**Comment by Licho1** [comment]
Autocomplete works this way, if you write this is zk it will autocompelte some threads. But if you do full search it will list any thread that contains a post which contains all the words from query.

**Comment by Skasi** [comment]
So why does it link to multiple different posts from the same thread instead of linking to the thread as a whole or the post that contains the words?

**Comment by knorker** [comment]
One can search for anything, like "overdrive", "Autobahnschnitzelwagen" or "Blackholeenergydriller" or "sdfgsdfgsdfgsdfgdsfg" and the search always returns the **same** 100 results.

**Comment by Licho1** [comment]
oh lol, that really does make it a bit useless :)

**Comment by Jamanno** [comment]
this is still a issue

**Comment by KingRaptor** [comment]
Fixed in afd8884f5bfcead7dfb012315e8ddc5ead2ea79f
Thanks to knorke for "nagging" us again about this. (no sarc!)

**Comment by Skasi** [comment]
`*`writes down a note`*` "Annoy devs more about existing bugs."

**Comment by knorker** [comment]
Thanks for the efforts.
For me the forum search did still not work. I thought this was because the fix had not been set live yet.

But appearently it is already supposed to work, at least that is what I was told here:
http://zero-k.info/Forum/Thread/20908?postID=150610#150610

> "the forum search function works flawless. "

This is the results of searching for "autobahn", a word that does not appear in any of the returned posts:

![zk forum search](https://cloud.githubusercontent.com/assets/3044855/12607849/47a02140-c4d8-11e5-9832-0ec9220d9534.png)

Note the timestamps, it is simply 100 last posts in forum. The results are the same no matter what you enter.

The "filter" function only returns threads, but not the post where the search-string appears.
That makes it unuseful to find specifique posts.

![zk search 2](https://cloud.githubusercontent.com/assets/3044855/12607919/c12ed290-c4d8-11e5-9025-5b24e2ccbf5a.png)

**Comment by Skasi** [comment]
Your first image **does not show the forum search function**. The forum search function is in the forum http://zero-k.info/Forum duh!

The forum-wide Filter function does not need to return posts, only threads are needed. After you click on a result you can use the thread-specific Filter to find any post containing the word(s) you search for. If you want to go even deeper, then press Ctrl F and use your browser's search function.

**Comment by knorker** [comment]
On http://zero-k.info/Forum it is the same: text-entry field with a "search"-icon next to it.
Returned results are the same.

What excactly does my first picture show then?
-It has a text-entry field
-It has a search-icon
-It returns forum posts
Yet it is not supposed to be a forum search? Ooookay...?


> The forum-wide Filter function does not need to return posts

Yes, it does need to return posts. 
Preferbally it would also highlight where in the post the search-string appeared.
Threads can span multiple pages and it is cumbersome to continue search manually.
CTRL-F search manually for every page in a thread, is it 1920?

**Comment by KingRaptor** [comment]
The "filter" vs. "search" thing is indeed rather confusing and ideas to disambiguate will be welcome (probably best to make new issue though). 
But anyway the search with the magnifying glass icon does work in test.

**Comment by knorker** [comment]
> does work in test

On test-site? Or what do you mean?

I have no idea what else details to give on this.
 browser=firefox.
I tried clicking the icon and I tried pressing return in text field. Same results.

**Comment by KingRaptor** [comment]
Test site yeah (sorry was ambiguous)

**Comment by knorker** [comment]
On test.zero-k.info the forum-search seems to work.
(but ofc results are not up to date)
Is it maybe not yet deployed on real server or so?

**Comment by Skasi** [comment]
> How does your search look like?

Like this:
![forum search](https://cloud.githubusercontent.com/assets/132906/12626125/57a13e4e-c537-11e5-93fd-0720e6e7f0a8.png)

>  CTRL-F search manually for every page in a thread, is it 1920?

Not needed, use the thread specific search function.

**Comment by knorker** [comment]
That screenshot of "filter" looks the same as in my second picture.

> Not needed, use the thread specific search function.

I know of this. I thought this must be a bug because no other forum system requires such awkward two-step-search. 

First search for the thread, then search again for the post = waste of time!
Also that returns _only_ the post. The in-thread-post-search returns literally a page with only the post on it, it does not link to the position in the thread or so. That makes it impossible to read further from the found post.
