### ISSUE TITLE
(zKlobby) modoption to disable units is not userfriendly / too cryptic

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#894]
There is option to disable units.
It works by listing the internal unit names.

The internal unit names can only be found in sourcefiles or filenames and other cryptic ways.
New players can not realistically be expected to figure that out.
If this is supposed to be a feature for players then it needs to be easier to use.
If it is meant only for testing/admins then that should be made more clear.

example thread:
http://zero-k.info/Forum/Thread/20737

**Comment by sprunk** [comment]
Fixed, now accepts real unit names

**Comment by knorker** [comment]
still not sure if that makes it is useable for normal players.
(It is like having to know mapnames for !map command vs selecting maps by clicking on pictures)
imo would need something graphical, basically like the buildmenu and then you can allow/block units by clicking. But the whole thing is maybe a niche feature.

**Comment by GoogleFrog** [comment]
I made it accept real unit names but the UI is still awful. Users should not have to enter perfectly formatted strings into things!

**Comment by Licho1** [comment]
we could add full gui, client knows unit list, but it seems to me as a very low priority task

**Comment by Licho1** [comment]
ZKL discontinued, chobby is the savior (and it has the same issue)
